version: '3.1'

services:
  app:
    build: ./app
    ports:
      - 8070:80
    networks:
      - net
      
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    networks:
      - net

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8071:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - net

networks:
  net:
    driver: bridge
